FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
COPY public ./public
ENV PORT=8092
EXPOSE 8092
CMD ["npm", "run", "start"]