name: "elt_duckdb_portfolio"
version: "1.0.0"
config-version: 2

profile: "elt_duckdb_portfolio"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  elt_duckdb_portfolio:
    staging:
      +materialized: view
    marts:
      +materialized: table
