version: 2

models:
  - name: stg_customers
    description: "Cleaned customers from raw."
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]
      - name: signup_date
        tests: [not_null]

  - name: stg_orders
    description: "Cleaned orders from raw."
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: amount
        tests: [not_null]
      - name: status
        tests: [not_null]
